### ISSUE TITLE
Liftover convert hg38 to hg19

### ISSUE THREAD

**Issue by JingjingBai2021** [lawremi/rtracklayer#107]
Hi, 
I am trying to convert a list of snps from hg38 to hg19. 

Most of the snps have converted sucessfully with the same position in dbSNP. But some SNPs' positions are off 1.

Unconverted SNP: rs1385708574 BP: 98999310
Liftover converted: rs1385708574 BP:99651564
dbSNP: rs1385708574 BP:99651565 

How to fix these?
I converted data frame to GRanges object to lift the coordinates. SNP start and end were labeled the same.
Best,
Jingjing

**Comment by lawremi** [comment]
This is likely due to the imprecise nature of the lift over. This question is better suited for support.bioconductor.org. It's not clear (yet) that this is an issue with the package itself.
