### ISSUE TITLE
readGFF() has problems when facing too long lines in imported gff file

### ISSUE THREAD

**Issue by HajkD** [lawremi/rtracklayer#15]
Hi @lawremi, 

First of all thank you so much for developing such a useful tool.
I recently started using `rtracklayer` and truly appreciate your efforts in developing this great package.

While using `rtracklayer` for some plant species I stumbled upon an issue when
trying to import the NCBI RefSeq `gff-file` of `Arabidopsis thaliana`.

See example below: 

```r
install.packages("biomartr")
# 'getGFF()' retrieves the gff file from NCBI RefSeq and stores the path to
# the downloaded file in variable 'Ath_gff' 
Ath_gff <- biomartr::getGFF("refseq", "Arabidopsis thaliana", path = "gff_folder")
# import A thaliana gff via rtracklayer
Ath_gff_import <- rtracklayer::import(Ath_gff)

#' Error in readGFF(filepath, version = version, filter = filter) : 
#' reading GFF file: cannot read line 631691, line is too long
```
The traceback looks as follows:

>Traceback:
>        
>9. readGFF(filepath, version = version, filter = filter) 
>8. readGFFAsGRanges(con, version = version, colnames = colnames, 
>                 filter = list(type = feature.type), genome = genome, sequenceRegionsAsSeqinfo = >sequenceRegionsAsSeqinfo, 
>                 speciesAsMetadata = TRUE) 
>7. .local(con, format, text, ...) 
>6. import(FileForFormat(con), ...) 
>5. import(FileForFormat(con), ...) 
>4. rtracklayer::import(annotation_file)  

I was wondering if it would be possible to either check for these cases and then chop
these corrupt lines or simply throw them out (maybe issuing a warning message) during
the import procedure?

Your help with this is truly appreciated.

Kind wishes,
Hajk

```r
> sessionInfo()
R version 3.5.2 (2018-12-20)
Platform: x86_64-apple-darwin15.6.0 (64-bit)
Running under: macOS Sierra 10.12.6

Matrix products: default
BLAS: /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib
LAPACK: /Library/Frameworks/R.framework/Versions/3.5/Resources/lib/libRlapack.dylib

locale:
[1] en_GB.UTF-8/en_GB.UTF-8/en_GB.UTF-8/C/en_GB.UTF-8/en_GB.UTF-8

attached base packages:
[1] stats4    parallel  stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] bindrcpp_0.2.2      biomartr_0.9.9000   Biostrings_2.50.2   XVector_0.22.0      IRanges_2.16.0      S4Vectors_0.20.1    BiocGenerics_0.28.0
```

**Comment by lawremi** [comment]
Perhaps @hpages could help here, as he wrote the optimized GFF reading.

**Comment by Roleren** [comment]
Any updates? 
This is still a problem for among others the Arabidopsis thaliana gff from refseq

**Comment by Roleren** [comment]
As a note, for possible improvement, here is a easy fix for many of these bad refseq genomes.
`
system("cat ~/Desktop/test_plant/Arabidopsis_thaliana_genomic_refseq.gff | awk '{ if (length($0) < 32768) print }' > ~/Desktop/test_plant/Arabidopsis_thaliana_genomic_refseq_trimmed2.gff")`

This trimmed version of the gff is imported successfully by rtracklayer.

**Comment by HajkD** [comment]
Hi Håkon,

Nice to hear from you again! :)

I wrote a checker function for this issue a while back in my [orthologr](https://github.com/drostlab/orthologr) package. 

https://github.com/drostlab/orthologr/blob/master/R/check_annotation.R

I hope this helps until this issue is resolved here?

Cheers,
Hajk

**Comment by hpages** [comment]
Hi guys,

I completely missed this sorry. Should be fixed in **rtracklayer** 1.52.1 (BioC release) and 1.53.1 (BioC devel). No chop or drop mechanism for now, just increased the length of the input buffer from 65536 to 200000 (longest line I saw in the [RefSeq GFF file for TAIR10.1](https://ftp.ncbi.nlm.nih.gov/genomes/all/GCF/000/001/735/GCF_000001735.4_TAIR10.1/GCF_000001735.4_TAIR10.1_genomic.gff.gz) was 168975 chars long).

Cheers,
H.

**Comment by Roleren** [comment]
Thanks a lot, then this issue can be closed when Hajk sees this, there is no more problems to address then I guess :)

**Comment by HajkD** [comment]
Wonderful! Thank you very much for fixing this issue and for your kind reminder!
