### ISSUE TITLE
generating track hubs with bigBeds?

### ISSUE THREAD

**Issue by tdhock** [lawremi/rtracklayer#19]
Hey @lawremi one of my packages currently depends on ucsc command line programs, and I would like to drop that dependency to make it more portable, https://github.com/tdhock/PeakSegPipeline/issues/15

two questions.

1. is it possible to create a track hub using rtracklayer? currently I am manually generating the track hub meta-data files (hub.txt, genomes.txt, trackDb.txt) and I was wondering if rtracklayer could do that for me? (or is there another bioc pkg for that?)

2. does rtracklayer support export to bigBed yet? I found this thread https://grokbase.com/t/r/bioconductor/12c293pab8/bioc-bigbed-support-in-rtracklayer which seems to indicate bigBed was not supported in 2012, and I still don't see any references to bigBed in rtracklayer R code. If bigBed is not supported, is there another way I can use rtracklayer to convert a bed file (essentially a list of genomic regions that I want to display with a color and text label that is specific to each region) to a binary file that can be used on a ucsc track hub?

Thanks

**Comment by lawremi** [comment]
Neither of those things are supported. Track hubs would be a nice feature; I just haven't used them yet. Please feel free to contribute if you have something.

BigBed is a pretty heavy format to support. Most of the time a tabixed BED suffices. Have you considered that?

**Comment by tdhock** [comment]
The UCSC track hub docs does not list tabixed BED as a supported file format genome.cse.ucsc.edu/goldenPath/help/hgTrackHubHelp.html so I don't think it is possible to display on a track hub.

**Comment by tdhock** [comment]
both projects would make good Google Summer of Code projects for students next year, I think. Have you ever participated in GSOC? Would you be willing to co-mentor a student with me next year?

**Comment by lawremi** [comment]
Yes. Sure. It's really too bad that they don't generally support tabix. They already support it for VCF. I wonder if it's worth approaching UCSC about that.

**Comment by tdhock** [comment]
Do you know anyone at UCSC you could ask? I don't have very good luck asking UCSC for feature requests...

I created a web page describing the project for next year's GSOC. https://github.com/rstats-gsoc/gsoc2020/wiki/rtracklayer-improvements please feel free to add details and edit as you like. In particular could you please write something in the "tests" section? Tests are mini tasks that we can assign potential students -- we can judge which student to accept by the quality of their test results. For this project I think we should ask potential students to demonstrate proficiency with C coding and with the bigBed / track hub meta-data file formats.

**Comment by lawremi** [comment]
I reached out to UCSC but they seem content with the existing features.

Thanks for putting together that proposal. I don't recall whether those proposals compete with others, but we could embellish the language a little, particularly around the impact of improving a core package like rtracklayer.

UCSC also recently added an API for accessing data that we have so far retrieved via awkward interaction with the table browser. That would be another good GSOC project. Shall I add it to the document?

**Comment by tdhock** [comment]
too bad about the feature request, that is what I expected.

for the data access API idea, please add to that wiki page if you think it falls under the theme of "rtracklayer improvements" otherwise if it is quite different then feel free to make a new wiki page.

the proposals do compete with others, but the primary challenge is finding a good student; usually if we get a good student who writes a good application it should be accepted. the primary purpose of the wiki page is to attracted talented students.

**Comment by lawremi** [comment]
I updated the proposal.

**Comment by tdhock** [comment]
looks good, let's hope to hear from some interested students around the application period (Jan-Mar 2020)

**Comment by lawremi** [comment]
This was fixed by #22. See https://github.com/lawremi/rtracklayer/blob/master/man/TrackHubGenome-class.Rd for some documentation.

**Comment by lawremi** [comment]
A vignette is a good idea. I'll bring that up with Sanchit at our next meeting. For right now, see the examples in the Rd files.

**Comment by maximilianh** [comment]
> Yes. Sure. It's really too bad that they don't generally support tabix. They already support it for VCF. I wonder if 
> it's worth approaching UCSC about that.

just found this: bigBed has more features than tabix. We have multiple indices, a schema description, it's a single-file format which is easier on cloud providers and doesn't require a second file. We have binary versions of bedToBigBed for most operating systems so I don't know what it's harder than running tabix.
