### ISSUE TITLE
New change to import.bw causes issue when importing specific regions?

### ISSUE THREAD

**Issue by MalteThodberg** [lawremi/rtracklayer#20]
Just came back from vacation to a build error in the CAGEfightR package that depends heavily on the rtracklayer package for BigWig IO.

I think I've tracked down the issue to this small example that used to work:
```# Example data
library(CAGEfightR)
data("exampleDesign")
head(exampleDesign)

# Locate files on your harddrive
bw_plus <- system.file("extdata", 
                       exampleDesign$BigWigPlus, 
                       package = "CAGEfightR")

# Make some tiles
genome <- SeqinfoForUCSCGenome("mm9")
grl <- GenomicRanges::tileGenome(genome, tilewidth = 100000000L)

# Importing everything works
import(bw_plus[[1]])

# Importing a tile doesn't
import(bw_plus[[1]], which=grl[[1]])
```

It gives an error related related to the naming of the seqlevels, which I haven't seen before:

Error in GenomeInfoDb:::makeNewSeqnames(x, new2old = new2old, seqlevels(value)) : 
  when 'new2old' is NULL, the first elements in the
  supplied 'seqlevels' must be identical to 'seqlevels(x)'

Is this intended behaviour, in which case I will update CAGEfightR?

**Comment by lawremi** [comment]
Please try GenomicRanges 1.37.15 and rtracklayer 1.45.5.

**Comment by MalteThodberg** [comment]
I will have a look once the new versions make it into devel!

**Comment by MalteThodberg** [comment]
Hello again @lawremi ,

Forgive me, but I'm a bit confused now:

The build error was resolved on the BioC devel branch (although a new one popped up).

However, the same build error still persists on the current stable branch 3.9.

Were the breaking changes to rtracklayer committed directly to the stable branch? In that case, will you also add the bug fix there?

**Comment by lawremi** [comment]
Just ported stuff to release.
