### ISSUE TITLE
GSoC 2020 : Track Hub feature doubts

### ISSUE THREAD

**Issue by sanchit-saini** [lawremi/rtracklayer#24]
Hi @lawremi @tdhock
I have a few doubts regarding the design and behavior of `TrackHubGenome` class in `rtracklayer`. Currently, it represents hierarchical tracks like this:
```R
            object$parent_track_name$child_track_name
```             
Above expression can go deeper if child track has another child track in it something like :
```R
            object$parent_track_name$child_track_name$child_child_track_name
```        
so doubts are:
1.  How hierarchical tracks should be represented in `rtracklayer` interface?
     (do we need to maintain the parent-child relationship or can we store all tracks on the same level?)
2.  What functions are expected for the trackDb file in `TrackHubGenome` class?

**Comment by tdhock** [comment]
1. I would just use the names / character strings to represent the hierarchy, as in the track hub file. here is an example from https://github.com/tdhock/nc/blob/master/inst/extdata/trackDb.txt.gz?raw=true 
```
track bcell

 track bcell_McGill0091
 parent bcell

  track bcell_McGill0091Coverage
  parent bcell_McGill0091

  track bcell_McGill0091Peaks
  parent bcell_McGill0091
```
in R you could represent this as a data table with 4 rows (one for each track) and two character columns (track/parent).

**Comment by lawremi** [comment]
What @tdhock suggestions is a good idea. Other options include: just making a nested list structure (which might map to how the user wants to navigate the structure anyway) or using the graph package or a similar package to represent the tree (downside is that it introduces a dependency).

**Comment by sanchit-saini** [comment]
Thanks for all the help and suggestions.
I'm closing this as it is resolved now.
