### ISSUE TITLE
export.bw() fails on a GPos object but succeeds if converted by GRanges() first.

### ISSUE THREAD

**Issue by charles-plessy** [lawremi/rtracklayer#29]
Here is a [link to a GPos object](https://www.dropbox.com/s/ai9itm586clt4y9/gp.Rds?dl=0) that makes the `export.bw()` crash with an error such as:

```
rsession: 1730343 1730344 doesn't intersect 1892288 1899678, chromId 6
chromSize 5022195: Resource temporarily unavailable
Error in isSingleString(path) : UCSC library operation failed
In addition: Warning message:
In isSingleString(path) : Internal error ucsc/bbiWrite.c 414
```

Bisecting the object did not isolate a problematic part, and removing enough entries at the head or at the tail suppressed the error.

Just converting with a call to `GRanges()` entirely solves the problem, but it would be nice to not have to do so.

The version of _rtracklayer_ that I tried is 1.49.3.  [Full session info available on the bioc-devel archive](https://stat.ethz.ch/pipermail/bioc-devel/2020-July/017001.html).

**Comment by christyvj** [comment]
I am also getting this message when I use CAGEr  exportCTSStoBedGraph(). I am new to analysing CAGE data and was wondering if you wouldn't mind sharing the code for using GRanges() as a work around? Thank you.
