### ISSUE TITLE
import.bb failing for certain web-hosted bigBed

### ISSUE THREAD

**Issue by vjcitn** [lawremi/rtracklayer#42]
```
> yy = "http://bedbase.org/api/bed/78c0e4753d04b238fc07e4ebe5a02984/file/bigbedfile"
> import.bb(yy, format="bigBed")
Error in seqinfo(con) : UCSC library operation failed
In addition: Warning message:
In seqinfo(con) :
  Couldn't open http://bedbase.org/api/bed/78c0e4753d04b238fc07e4ebe5a02984/file/bigbedfile
```
When this content is retrieved to local system, import.bb can import it.  I have also succeeded with
import.bb for bigBed content in NCBI ftp.    Efforts to debug bbiFileOpen.c are not working out so far.
Any hints appreciated.
```
R version 4.0.3 Patched (2021-01-30 r79907)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 20.04 LTS (fossa-melisa X20)

Matrix products: default
BLAS:   /home/stvjc/R-4-0-dist/lib/R/lib/libRblas.so
LAPACK: /home/stvjc/R-4-0-dist/lib/R/lib/libRlapack.so

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C              
 [3] LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8    
 [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8   
 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C            
[11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] parallel  stats4    stats     graphics  grDevices utils     datasets 
[8] methods   base     

other attached packages:
[1] rtracklayer_1.50.0   GenomicRanges_1.42.0 GenomeInfoDb_1.26.2 
[4] IRanges_2.24.1       S4Vectors_0.28.1     BiocGenerics_0.36.0 
[7] rmarkdown_2.7       

loaded via a namespace (and not attached):
 [1] rstudioapi_0.13             knitr_1.31                 
 [3] XVector_0.30.0              GenomicAlignments_1.26.0   
 [5] zlibbioc_1.36.0             BiocParallel_1.24.1        
 [7] lattice_0.20-41             rlang_0.4.10               
 [9] tools_4.0.3                 grid_4.0.3                 
[11] SummarizedExperiment_1.20.0 Biobase_2.50.0             
[13] xfun_0.21                   matrixStats_0.58.0         
[15] htmltools_0.5.1.1           digest_0.6.27              
[17] crayon_1.4.1                Matrix_1.3-2               
[19] startup_0.15.0              GenomeInfoDbData_1.2.4     
[21] bitops_1.0-6                RCurl_1.98-1.2             
[23] evaluate_0.14               DelayedArray_0.16.2        
[25] compiler_4.0.3              MatrixGenerics_1.2.1       
[27] Biostrings_2.58.0           Rsamtools_2.6.0            
[29] XML_3.99-0.5               
> 

```

**Comment by sanchit-saini** [comment]
The kent library does all the heavy lifting of the managing resource. rtracklayer relies on it and provides an interface for bigBed format.

In your case URL is redirecting to other URL
```console
~ ❯❯❯ curl http://bedbase.org/api/bed/78c0e4753d04b238fc07e4ebe5a02984/file/bigbedfile -v

*   Trying 52.206.204.252:80...
* Connected to bedbase.org (52.206.204.252) port 80 (#0)
> GET /api/bed/78c0e4753d04b238fc07e4ebe5a02984/file/bigbedfile HTTP/1.1
> Host: bedbase.org
> User-Agent: curl/7.75.0
> Accept: */*
>
* Mark bundle as not supporting multiuse
< HTTP/1.1 307 Temporary Redirect
< Server: nginx/1.19.6
< Date: Thu, 04 Mar 2021 04:45:09 GMT
< Transfer-Encoding: chunked
< Connection: keep-alive
< location: http://data.bedbase.org/outputs/bedstat_output/../../bigbed_files/GSE105587_ENCFF018NNF_conservative_idr_thresholded_peaks_GRCh38.bigBed
<
* Connection #0 to host bedbase.org left intact
```
[bigBedFileOpen](https://github.com/lawremi/rtracklayer/blob/9221c8e8e7086940eca43f5a78ee35535a82ab74/src/ucsc/bigBed.c#L26) -> [bbiFileOpen](https://github.com/lawremi/rtracklayer/blob/9221c8e8e7086940eca43f5a78ee35535a82ab74/src/ucsc/bbiRead.c#L92) -> [udcFileOpen](https://github.com/lawremi/rtracklayer/blob/f3f9612101dd5cf6bd57a985f6ff665da9287b81/src/ucsc/udc.c#L931) -> [udcFileMayOpen](https://github.com/lawremi/rtracklayer/blob/f3f9612101dd5cf6bd57a985f6ff665da9287b81/src/ucsc/udc.c#L835-#L925)

It seems URL redirection was not handled properly when rtracklayer pull the code from the kent library. It appears kent library had modified a lot of code that handles the reading of the resource. Therefore I pulled the latest stable code(v411) and created a [quick and dirty integration](https://github.com/sanchit-saini/rtracklayer/commit/1ea1f337f7673a095657ea06a12c2da9dc31651c) just to test it.From initial observation looks like it is not fixed yet.

For now, you can do something like:
```R
library(rtracklayer)
library(RCurl)

# warning: it's just a hack, it is not robust
# Read header response and retrieve redirection location from it.
# It fails for the binary resource (direct bigbed file) 
# so in error handler it directly returns the passed URL back
redirect_handler <- function(url) {
    tryCatch(
        expr = {
            response <- getURL(url, header = T)
            headers <- strsplit(response, "\r\n")[[1]]
            position <- grep("location:", headers)
            redirected_url <- sub("location: ", "", headers[position])
            if (redirected_url != "NA")
                redirected_url
            else url
            },
        error = function(e) {
                return(url)
            }
    )
}

url <- "http://bedbase.org/api/bed/78c0e4753d04b238fc07e4ebe5a02984/file/bigbedfile"
url <- redirect_handler(url)
import.bb(url, format="bigBed")
```

**Comment by lawremi** [comment]
Good idea to do it at the R level. It would probably be a bit cleaner to just use the HTTP `HEAD` command so that you just get the header. Probably worth engaging with the UCSC people on this. I would be surprised if the Kent library does not support redirects.

**Comment by vjcitn** [comment]
Thanks @sanchit-saini this is really helpful.  Will this change go into rtracklayer in devel?  Do we need to
engage with UCSC or is that something you will do?  Feel free to close issue if ready.

**Comment by sanchit-saini** [comment]
> Will this change go into rtracklayer in devel?

Yes, but only if UCSC folks fix the URL redirection issue.

> Do we need to engage with UCSC or is that something you will do?

Yes, last week It was not certain that kent library was responsible for the issue. As the patch was created quickly so it was possible integration was not perfect. Just to be sure, I Isolated `udcFileMayOpen` function to test and now I'm certain kent does not handle URL redirection properly even with the v411 release.

**Comment by sanchit-saini** [comment]
Hi @vjcitn,
The issue here is the server is not responding properly to HEAD requests. 
If the server responds with the proper redirect HTTP status code then this should work fine. 
more details : https://github.com/ucscGenomeBrowser/kent/issues/53#issuecomment-794337113

And for integration of URL redirection feature with rtracklayer. 
I'll make new clean integration it might be finished by this week.

**Comment by sanchit-saini** [comment]
This issue can be closed now as change had been integrated so URL redirection should work.

**Comment by vjcitn** [comment]
Immense thanks!
