### ISSUE TITLE
getTable() produces a Bad Request error

### ISSUE THREAD

**Issue by hpages** [lawremi/rtracklayer#5]
Hi @lawremi 

It seems that `getTable()` started to fail more than one week ago with a "Bad Request" error when trying to get some UCSC tables e.g.:
```
library(rtracklayer)
session <- browserSession()
genome(session) <- "sacCer2"
query <- ucscTableQuery(session, "Assembly")
df <- getTable(query)
#Error: Bad Request
```
This also happens with the other organism/track combinations that I tried (e.g. hg19/Assembly and hg19/ensGene).

I noticed that a new version of RCurl (1.95-4.10) showed up on CRAN around the time that `getTable()` started to fail:

  https://cran.r-project.org/web/packages/RCurl/index.html

Could it be the culprit? Or could it be that something has changed on UCSC side?

This affects GenomicFeatures on Linux and Windows in Bioconductor release:

  https://bioconductor.org/checkResults/3.6/bioc-LATEST/GenomicFeatures/

and on Linux in Bioconductor devel:

  https://bioconductor.org/checkResults/3.7/bioc-LATEST/GenomicFeatures/

Including @mtmorgan and @vobencha 

Thanks,
H.

**Comment by lawremi** [comment]
Most likely something on the UCSC side. It does not fail reliably for me.

**Comment by hpages** [comment]
Sorry but I have to ask: are you planning to do something about this?

**Comment by lawremi** [comment]
Of course.

**Comment by hpages** [comment]
Sounds good, thanks! This is confirmed by `R CMD check` failing on Linux but not on Mac for GenomicRanges in release:
  https://bioconductor.org/checkResults/3.6/bioc-LATEST/GenomicRanges/

**Comment by lawremi** [comment]
Btw, I did a diff of the old and new RCurl packages but it looks like it just fixes `(char *)` warnings. I think UCSC has been doing some hacking on the website. I had to make a change to parsing a couple months ago.

**Comment by lawremi** [comment]
I did manage to reproduce it in Linux. The error always occurrs in the upload of the query regions to the table browser. In many cases (like the example above), this is unnecessary, because we can just ask for the whole genome. It looks like there was a bug that prevented that shortcut. With 1.39.5, it no longer attempts the upload in the whole genome case, so it should be more stable.

**Comment by hpages** [comment]
`getTable()` seems to work again with rtracklayer 1.39.5. Thanks!

**Comment by hpages** [comment]
Re-opening this issue as the problem actually persists in release (rtracklayer 1.38.3) and devel (rtracklayer 1.39.8) when the query is prepared by calling `ucscTableQuery` with the `names` argument:
```
library(rtracklayer)
session <- browserSession()
genome(session) <- "mm10"
query <- ucscTableQuery(session, "knownGene", names="uc007aet.1")
df <- getTable(query)
#Error: Bad Request
```
Thanks,
H.

**Comment by lawremi** [comment]
This is a different POST but I guess the same underlying problem. It is strange that there are failures specific to the client OS. I guess one way to diagnose would be to issue POSTs to a local server and check for variation in the logs. But it could be specific to the UCSC network configuration, or something.

**Comment by lawremi** [comment]
I've made some optimizations to the table browser to reduce the number of HTTP requests. I can't reproduce the issue with the named feature anymore, at least on linux. The table browser stuff was never really meant to be used for batch downloading, so it's a good idea to move to SQL.

**Comment by drosophila92** [comment]
Hi @lawremi

I'm following a GWA tutorial by [Reed et al., 2015](https://onlinelibrary.wiley.com/doi/full/10.1002/sim.6605) and learning how to make regional association plots for candidates SNPs around CETP gene locus. Query "uc002eki.2" and"uc002ekj.2" can be retrieved directly from UCSC genome browser and seem to be two haplotypes of CETP.

However, I also have problem with getTable()  - it returns the same "Bad Request" error when I tried to get some UCSC tables e.g.:

library(rtracklayer)
session <- browserSession()
genome <- "hg19"
chromosome <- "chr16"
maxRange <- 57022352L
minRange <- 56990716L
tbl <- "kgXref"
query2 <- ucscTableQuery(session, "knownGene", 
                         GRangesForUCSCGenome(genome, chromosome, 
                                              IRanges::IRanges(minRange, maxRange)), table = tbl, 
                         names = c("uc002eki.2", "uc002ekj.2"))
t1 <- getTable(query2)

I'm new to Bioconductor packages and probably not understand the black boxes. Could you help me with this problem?

Sincerely,
Yige

**Comment by lawremi** [comment]
Please make this a separate issue. It would help to see your `sessionInfo()`, because I don't get the bad request error. It looks like data for the entire genome is returned, however, so something is not right. This summer we will be rewriting the table browser to use the new UCSC REST API, which should be a lot more robust.
