### ISSUE TITLE
Import bigwigs via http on Windows machine

### ISSUE THREAD

**Issue by slaish** [lawremi/rtracklayer#57]
In #52 there is a comment from June 9: 'Support for reading bigwigs on Windows is probably still a bit shaky.' 
We find that the import function can read bigwig-files stored locally, but not from http, whereas it can read bed-files stored both locally and via http. 
Will this issue be fixed at some point or do we need to find a workaround for Windows-users?

**Comment by lawremi** [comment]
BED files are handled by R connections so get http support for free. BigWigs are parsed by the UCSC library, which has its own http implementation that does not support Windows. Simplest workaround would be to transfer the file to local storage, perhaps using BiocFileCache. However, that would defeat some of the benefit of BigWig.

**Comment by sanchit-saini** [comment]
@lawremi  This could be closed, now we are relying on the libcurl which also works out of the box on windows too.
