### ISSUE TITLE
import.bed

### ISSUE THREAD

**Issue by Roleren** [lawremi/rtracklayer#6]
Thanks for a great package, I just tested import.bed compared to data.table::fread, and the time difference is huge. I looked through the code and I know you need to do some checks from the first line to see what the columns are. But in line 302:  
bed <- DataFrame(read.table(con, colClasses = bedClasses,
                                          as.is = TRUE, na.strings = ".",
                                          comment.char = "",
                                          sep = "\t",
quote = "\""))

Could not this be done more efficiently, e.g. ribo-seq reads are many million rows, and this process takes minutes to load into R.

If this is something your not going to do, just delete my post. 
Thanks

**Comment by lawremi** [comment]
How do you suggest that I improve that line? Have you done any actual profiling?

**Comment by Roleren** [comment]
Yeah, did profiling on ribo-seq:

Rprof()
90% of time is in this function calling:
"scan" "read.table" "DataFrame" ".local" "import" "standardGeneric" "import" "import" "standardGeneric" "import" "import.bed" "standardGeneric" "import.bed" 

that is line 302

Problem I think is that its done line by line in R, if I am right..
What would be best would be to:
first load only first line, check which bed format it is, and that the line is valid, then:
load it all in one go:
 expect everything to be correct, and then check afterwards, if it actually was.

One problem then is that in the function:
 GenomicData() line 344
, you can group by exons(that is: IRanges can take several starts and stops), but if you read it all in at ones, you need to know how to group.
This way of doing it is done with, e.g. GenomicRanges::makeGRangesListFromDataFrame

Where you include a split.field column, if that makes sense.

**Comment by lawremi** [comment]
> Problem I think is that its done line by line in R, if I am right..
> What would be best would be to:
> first load only first line, check which bed format it is, and that the line is valid, then:
> load it all in one go:
> expect everything to be correct, and then check afterwards, if it actually was.

I am pretty sure that is exactly what the code is doing. I don't see a loop over the lines anywhere. No surprise that `read.table()` would take the majority of the time. No easy way to speed it up. I made some gains a while ago by adding buffered reading to R's connections, but it's a long way from the hyper-optimized `fread()` that relies on `mmap()` and other tricks.

> 
> 
> One problem then is that in the function:
> GenomicData() line 344
> , you can group by exons(that is: IRanges can take several starts and stops), but if you read it all in at ones, you need to know how to group.
> This way of doing it is done with, e.g. GenomicRanges::makeGRangesListFromDataFrame

But we're not making a GRangesList here, so I'm a bit confused.

**Comment by Roleren** [comment]
Yes, I was a bit unclear, my question really is, fread uses a lot of cool stuff, would it take too long to make these fast type parsers into import.bed ?

**Comment by lawremi** [comment]
You mean just use `fread()` instead of `read.table()`? How much speedup does it get you? How big is your data? Are you sure BED is the right format for it?

**Comment by Roleren** [comment]
yeah, it works, so this was a timing on one of my smaller files:

# this is with fread and convert to granges:
system.time(ORFik:::cageFromFile(standardRFP))
Read 19272715 rows and 6 (of 6) columns from 0.669 GB file in 00:00:08
   user  system elapsed 
 10.972   1.129  12.198 

> system.time(import.bed(standardRFP))
   user  system elapsed 
 51.012   2.511  53.505 

Difference her is not terrible on small ones, but here is an example on a much bigger file:

# This is my biggest file:


# this is with fread and convert to granges:
> system.time(ORFik:::cageFromFile(s))
Read 182154065 rows and 6 (of 6) columns from 6.489 GB file in 00:01:05
   user  system elapsed 
 83.588  15.385  98.913 

> system.time(import.bed(s))
   user  system elapsed 
494.536  31.597 525.994 

Here it's starting to get a bit long, but looks like a stable 5x time from fread, what do you think ?
I could have made fread even faster by specifying columns etc, but this just shows the concept.

**Comment by lawremi** [comment]
Looks like a decent speedup. I don't want to depend on data.table, though. Base R needs faster table reading...

**Comment by Roleren** [comment]
Yes, I see that point, but maybe it's time package creators started depending on it ? Big data is coming, and a lot of functions in R are way too slow, you think the best is to wait for R to make a faster version  of read.table ?

**Comment by lawremi** [comment]
I'm not sure if 5X slower qualifies as "way too slow" when there are often many other bottlenecks, especially in an analysis on 182 million rows. It's a shame that we are stuck with tab-separated files for data of this magnitude.

Also, I'm not really waiting for R to become faster. As a member of R core, I'm trying to motivate myself to do it ;)

**Comment by Roleren** [comment]
Yeah, I consider it solved then, I'll use my function for now. Good luck with read.table then :)
