### ISSUE TITLE
`import.bw()` fails with long file names

### ISSUE THREAD

**Issue by mtmorgan** [lawremi/rtracklayer#65]
This works
```
url <- "http://genome.ucsc.edu/goldenPath/help/examples/bigWigExample.bw"
import.bw(long_url)
```
but creating a longer 'name' for the file (the `?...` are ignored by the server; the use case comes from 'signed' URLs where the query includes authentication information)
```
set.seed(123)
long_url <- paste0(url, "?", paste(sample(letters, 500, TRUE), collapse = ""))
import.bw(long_url)
```
leads to the error
```
File name too long
Error in seqinfo(ranges) : UCSC library operation failed
In addition: Warning message:
In seqinfo(ranges) :
  Couldn't make directory /tmp/udcCache_ma38727/http/genome.ucsc.edu/goldenPath/help/examples/bigWigExample.bwQ3Fosncjrvketnvyzesyyichzgjisdnqkgulojmgiijwugufybehlmrayyfuoiozptfkhvvgpqvrqbdmevsytvynywchplyncngcwvzouehsjrjlbjvltnqnvchnsoxqwkgowzfngjefpxuwkdlnsygvzigbpmsxtogdahtypxvkpthcdtlvqjtkywhnumbkmnfyhlzdmnupwahhjyhruiggzjxvwzkaysjuvmkkytzgywztxyiiewnnfazjqzqzuguzitfrqeytcynabdjaeuyhwyumrjfgipqumuhugtrqabqbmxqcrbelymjfjjfppcdcwcpbowcigidbvzlikgmekaslbuqlcyrovcsyrqfjhjzmtfttiphgjqrhsjwkqlbsmmsvjpedrapqlub
```
A solution might be to more completely separate the url into a correct 'basename', or create a simple hash (e.g., djb2 of http://www.cse.yorku.ca/~oz/hash.html) of the path and use that as the 'key' to store in 'udcCache'.

**Comment by lawremi** [comment]
Sounds like an upstream issue that we should at least report. I wonder if @sanchit-saini could find a temporary fix?

**Comment by sanchit-saini** [comment]
Yes, I looked at the codebase and I think it might be possible to fix it. I'll create a PR soon

**Comment by mtmorgan** [comment]
Reporting that this solved my problem, thanks!
